disallowed-methods = [
    # Shouldn't need to access these directly
    "revolt_database::models::bots::model::Bot::remove_field",
    "revolt_database::models::messages::model::Message::attach_sendable_embed",

    # Prefer to use Object::create()
    "revolt_database::models::bots::ops::AbstractBots::insert_bot",
    "revolt_database::models::channel_invites::ops::AbstractChannelInvites::insert_invite",
    "revolt_database::models::channel_unreads::ops::AbstractChannelUnreads::acknowledge_message",
    "revolt_database::models::channel_webhooks::ops::AbstractWebhooks::insert_webhook",
    "revolt_database::models::bots::ops::AbstractBots::update_bot",

    # Prefer to use Object::delete(&self)
    "revolt_database::models::bots::ops::AbstractBots::delete_bot",
]
