disallowed-methods = [
    # Shouldn't need to access these directly
    "revolt_database::models::bots::model::Bot::remove_field",
    "revolt_database::models::messages::model::Message::attach_sendable_embed",

    "revolt_database::models::emojis::ops::AbstractEmojis::insert_emoji",
    "revolt_database::models::files::ops::AbstractAttachments::insert_attachment",
    "revolt_database::models::messages::ops::AbstractMessages::insert_message",
    "revolt_database::models::ratelimit_events::ops::AbstractRatelimitEvents::insert_ratelimit_event",
    "revolt_database::models::server_bans::ops::AbstractServerBans::insert_ban",
    "revolt_database::models::server_members::ops::AbstractServerMembers::insert_member",
    "revolt_database::models::servers::ops::AbstractServers::insert_server",
    "revolt_database::models::users::ops::AbstractUsers::insert_user",

    # Prefer to use Object::update(&self)
    "revolt_database::models::bots::ops::AbstractBots::update_bot",

    # Prefer to use Object::delete(&self)
    "revolt_database::models::bots::ops::AbstractBots::delete_bot",
]
